version: '3.9'

services:
  task-management-system:
    container_name: task-management-system
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - task-management-system-db-net
      - task-management-system-search-net
      - task-management-system-cache-redis-net
      - fusionauth-net
    ports:
      - "8080:8080"
    env_file:
      - docker/task-management-system/dev.env
    restart: unless-stopped
    depends_on:
      task-management-system-db:
        condition: service_healthy
      task-management-system-elasticsearch:
        condition: service_healthy
      task-management-system-cache-redis:
        condition: service_healthy
      fusionauth:
        condition: service_healthy

  task-management-system-elasticsearch:
    container_name: "task-management-system-search"
    image: elasticsearch:8.11.3
    networks:
      - task-management-system-search-net
    volumes:
      - task-management-system-search-data:/usr/share/elasticsearch/data
    env_file:
      - docker/task-management-system-search/elasticsearch/.env
    healthcheck:
      test: [ "CMD", "curl",  "--fail" ,"--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://localhost:9200/" ]
      interval: 5s
      timeout: 5s
      retries: 15
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped

  task-management-system-db:
    container_name: task-management-system-db
    image: postgres:16.1-bullseye
    networks:
      - task-management-system-db-net
    env_file:
      - ./docker/task-management-system-db/postgres/.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - task-management-system-db-data:/var/lib/postgresql/datadb

  task-management-system-cache-redis:
    container_name: task-management-system-cache-redis
    image: redis:7.2.3-bookworm
    networks:
      - task-management-system-cache-redis-net
    volumes:
      - task-management-system-cache-redis-data:/data
      - ./docker/task-management-system-cache/redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  fusionauth-db:
    container_name: fusionauth-db
    image: postgres:12.9
    env_file:
      - ./docker/fusionauth-db/postgres/.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fusionauth-db-net
    restart: unless-stopped
    volumes:
      - fusionauth-db-data:/var/lib/postgresql/datadb

  fusionauth-search:
    container_name: fusionauth-search
    image: elasticsearch:8.11.3
    env_file:
      - ./docker/fusionauth-search/elasticsearch/.env
    healthcheck:
      test: [ "CMD", "curl",  "--fail" ,"--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://localhost:9200/" ]
      interval: 5s
      timeout: 5s
      retries: 15
    networks:
      - fusionauth-search-net
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - fusionauth-search-data:/usr/share/elasticsearch/data

  fusionauth:
    container_name: fusionauth
    image: fusionauth/fusionauth-app:latest
    depends_on:
      fusionauth-db:
        condition: service_healthy
      fusionauth-search:
        condition: service_healthy
    env_file:
      - ./docker/fusionauth/.env
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:9011" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fusionauth-net
      - fusionauth-db-net
      - fusionauth-search-net
    restart: unless-stopped
    ports:
      - "9011:9011"
    volumes:
      - fusionauth-config:/usr/local/fusionauth/config

networks:
  task-management-system-db-net:
  task-management-system-search-net:
  task-management-system-cache-redis-net:
  fusionauth-net:
  fusionauth-db-net:
  fusionauth-search-net:

volumes:
  task-management-system-db-data:
  task-management-system-search-data:
  task-management-system-cache-redis-data:
  fusionauth-db-data:
  fusionauth-config:
  fusionauth-search-data:
