/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.4/userguide/building_swift_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "task-management-system"
include("api")

dependencyResolutionManagement {
    versionCatalogs.create("libs") {
        plugin("spring-boot", "org.springframework.boot").version("3.2.0")
        plugin("spring-dependencyManagement", "io.spring.dependency-management").version("1.1.4")
        library("springdoc-swagger", "org.springdoc", "springdoc-openapi-starter-webmvc-ui").version("2.3.0")
        library("fusionauthSdk", "io.fusionauth", "fusionauth-java-client").version("1.50.0")
        library("bouncycastle.cryptoProvider", "org.bouncycastle:bcprov-jdk18on:1.78.1")
        library("userAgentParser", "com.github.ua-parser:uap-java:1.6.1")
        library("awsSdk.s3", "software.amazon.awssdk:s3:2.26.9")
    }
}
