sso:
  provider: fusionauth
  server: http://localhost:9011
  api-key: Hjd_wU5w_Kh4CfzFoEWTNB-YJoMqGJoO_x0kbpKy8M2T4Y6UGEuRn0MW
  tenant-id: 66596267-5933-e0aa-b3bc-8ac0344bed03
  application-id: f3c84053-b5ff-423f-b2b5-af690b7199b0
  access-token-age: 3600
  refresh-token-age: 43200
  files-access: http://localhost:8080/download?location=
  search-engine: elasticsearch

fs:
  files-path: files

spring:
  main:
    web-application-type: servlet
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/tms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false

  flyway:
    locations: classpath:db/migration

  elasticsearch:
    uris: localhost:9200
    username: elastic
    password: elastic

  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: ${sso.server}/.well-known/jwks.json
          jws-algorithms: RS256

  messages:
    basename: locale/messages

  data:
    web:
      pageable:
        default-page-size: 10

    elasticsearch:
      repositories:
        enabled: false

    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false
      password: redis

  cache:
    type: redis
    redis:
      time-to-live: 12h

springdoc:
  swagger-ui:
    csrf:
      enabled: true
    oauth:
      client-id: f3c84053-b5ff-423f-b2b5-af690b7199b0
      use-pkce-with-authorization-code-grant: true
      scopes: openid, email
      additional-query-string-params:
        authorization-uri: ${sso.server}/oauth2/authorize
        token-uri: ${sso.server}/oauth2/token
