sso:
  server: http://localhost:9011

spring:
  main:
    web-application-type: servlet
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/tms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false

  flyway:
    locations: classpath:db/migration

  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: ${sso.server}/.well-known/jwks.json
          jws-algorithms: ES384

  messages:
    basename: locale/messages

  data:
    web:
      pageable:
        default-page-size: 10

springdoc:
  swagger-ui:
    csrf:
      enabled: true
    oauth:
      client-id: 22adff03-0643-4cc9-9747-57284615c848
      use-pkce-with-authorization-code-grant: true
      scopes: openid, email, refresh_token
      additional-query-string-params:
        authorization-uri: ${sso.server}/oauth2/authorize
        token-uri: ${sso.server}/oauth2/token