sso:
  provider: fusionauth
  issuer: http://localhost:9011
  jwt-set-uri: ${sso.issuer}/.well-known/jwks.json
  jws-algorithm: RS256
  api-key: Hjd_wU5w_Kh4CfzFoEWTNB-YJoMqGJoO_x0kbpKy8M2T4Y6UGEuRn0MW
  tenant-id: 66596267-5933-e0aa-b3bc-8ac0344bed03
  application-id: f3c84053-b5ff-423f-b2b5-af690b7199b0
  files-access: http://localhost:8080/download?location=

# common
  access-token-age: 3600
  refresh-token-age: 43200
  search-engine: elasticsearch
  bearer-token-store-secret-hex: b08ebc4a4c5153a4fbe3574de17f1e02
  audiences:

# provider: local
  refresh-token-secret: eadf53e3e3364bdc91216e4045e78f8f42f9101eab0633b443be7c5e13567d3a # local provider
  refresh-token-algorithm: HmacSha512
  refresh-token-rotation: true
  bearer-token-type: jwt
  keystore: classpath:openssl/localhost.p12
  keystore-alias: localhost
  keystore-password: password
  keystore-key-password: password
  keystore-key-algorithm: RS256

fs:
  files-path: files

spring:
  main:
    web-application-type: servlet
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/tms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false

  flyway:
    locations: classpath:db/migration

  elasticsearch:
    uris: localhost:9200
    username: elastic
    password: elastic

  messages:
    basename: locale/messages

  data:
    web:
      pageable:
        default-page-size: 10

    elasticsearch:
      repositories:
        enabled: false

    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false
      password: redis

  cache:
    type: redis
    redis:
      time-to-live: 12h

springdoc:
  swagger-ui:
    csrf:
      enabled: true
    oauth:
      client-id: f3c84053-b5ff-423f-b2b5-af690b7199b0
      use-pkce-with-authorization-code-grant: true
      scopes: openid, email

swagger:
  oAuth2:
    issuer: ${sso.issuer}
